export const types = {
  UPDATE_STATE: 'UPDATE_STATE',
  SET_CURRENT_SONG: 'SET_CURRENT_SONG',
  SET_CURRENT_TIME: 'SET_CURRENT_TIME',
  SET_PLAYING_STATE: 'SET_PLAYING_STATE',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  SET_PLAY_LIST_SHOW: 'SET_PLAY_LIST_SHOW',
  SET_PLAYER_SHOW: 'SET_PLAYER_SHOW',
  SET_PLAY_LIST_PROMPT_SHOW: 'SET_PLAY_LIST_PROMPT_SHOW',
  SET_PLAY_LIST: 'SET_PLAY_LIST',
  SET_PLAY_HISTORY: 'SET_PLAY_HISTORY',
  SET_MENU_SHOW: 'SET_MENU_SHOW'
}
