name: Build app and deploy to tencentyun
on:
  #监听push操作
  push:
    branches:
      # main分支，你也可以改成其他分支
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.17.1'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.VUE_MUSIC_PC }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: dist # 这是要复制到服务器的文件夹名称
          REMOTE_HOST: '192.144.232.23' # 服务器公网地址
          REMOTE_USER: root # 腾讯云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /front-project/vue-music-pc # 打包后的 dist 文件夹将放在 /front-project/vue-music-pc